spring:
  security:
    #认证服务中心或认证服务中心地址
    auth_server: ${cj.geochat.security_auth_server_host:http://localhost:9000}
    whitelist:
      - /*/wagger-ui.html**
      - /*/doc.html**
    staticlist:
      - /assets/**
      - /css/**
      - /images/**
      - /js/**
      - /img/**
      - /*/webjars/**
      - /*/swagger-resources**
      - /*/*/api-docs**
      - /*/*.css
      - /*/*.json
      - /*/*.js
      - /*/*.ico
      - /*/*.jpg
      - /*/*.png
