spring:
  security:
    #认证服务中心或认证服务中心地址
    auth_server: ${cj.geochat.security_auth_server_host:http://localhost:9000}
    whitelist:
      - /*/swagger-ui.html
      - /*/doc.html
    staticlist:
      - /assets/**
      - /css/**
      - /images/**
      - /js/**
      - /img/**
