spring:
  redis:
    #singleten|sentinel|cluster
    mode: sentinel
    database: ${cj.geochat.spring.redis.db:0} # Redis Database index （ The default is 0）
    password: ${cj.geochat.spring.redis.password:123456} # Redis Server connection password （ The default is empty. ）
    timeout: ${cj.geochat.spring.redis.timeout:5000} # Connection timeout , Company ms
    sentinel:
      master: ${cj.geochat.spring.redis.sentinel.master:local-master}
      #网关内的依赖冲突，致使在mac m1芯片上不能解析域名，因此采用ip地址连接redis
      nodes: ${cj.geochat.spring.redis.sentinel.nodes:192.168.0.254:26379,192.168.0.254:26380,192.168.0.254:26381}
    lettuce:
      pool:
        max-active: 8 # Maximum number of connections in connection pool （ Use a negative value to indicate that there is no limit ） Default 8
        max-wait: -1 # Connection pool maximum blocking wait time （ Use a negative value to indicate that there is no limit ） Default -1
        max-idle: 8 # The maximum free connection in the connection pool Default 8
        min-idle: 0 # The smallest free connection in the connection pool Default 0
